[[redirects]]
  from = "/zoom/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/zoom/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors 'self' https://*.zoom.us https://*.zoom.com"
